version: 2
project_name: ets
before:
  hooks:
    - go mod download
builds:
  - env:
      # static binary to not depend on specific glibc versions
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
nfpms:
  - formats:
      - deb
      - rpm
    homepage: https://github.com/gdubicki/ets
    maintainer: Greg Dubicki <grzegorz.dubicki@gmail.com>
    description: >
      command output timestamper

      ets prefixes each line of a command's output with a timestamp.
    license: MIT
    contents:
      - src: "ets.1"
        dst: "/usr/share/man/man1/ets.1"
release:
  draft: true
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
