name: test
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: golangci-lint on .
        uses: golangci/golangci-lint-action@v6
        with:
          args: -E gofmt
      - name: golangci-lint on fixtures/basic
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: fixtures/basic
          args: -E gofmt
      - name: golangci-lint on fixtures/detect_tty
        uses: golangci/golangci-lint-action@v6
        with:
          working-directory: fixtures/detect_tty
          args: -E gofmt
      - name: golangci-lint on fixtures/signals
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: fixtures/signals
          args: -E gofmt
      - name: golangci-lint on fixtures/timed
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: fixtures/timed
          args: -E gofmt
      - name: golangci-lint on fixtures/winsize
        uses: golangci/golangci-lint-action@v4
        with:
          working-directory: fixtures/winsize
          args: -E gofmt

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Test
        run: |
          make test
